name: 'test-tf-refresh'

on:
  workflow_dispatch:

jobs:

  security_groups:
    name: 'security_groups'
    runs-on: ubuntu-latest
    environment: test
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/test/security_groups

    # Generates an execution plan for Terraform
    - name: Terraform Plan (Refresh Only)
      run: terraform plan -refresh-only -var-file=../test.tfvars
      working-directory: ./environments/test/security_groups


  iam:
    name: 'iam'
    runs-on: ubuntu-latest
    environment: test
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/test/iam

    # Generates an execution plan for Terraform
    - name: Terraform Plan (Refresh Only)
      run: terraform plan -refresh-only -var-file=../test.tfvars
      working-directory: ./environments/test/iam
