name: 'test-tf-destroy'

on:
  workflow_dispatch:

jobs:

  fargate_cluster:
    name: 'fargate_cluster'
    needs: 'task-definitions'
    runs-on: ubuntu-latest
    environment: test
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/test/fargate-cluster

    # Generates an execution plan for Terraform
    - name: Terraform Destroy Plan
      run: terraform plan -destroy -var-file=../test.tfvars
      working-directory: ./environments/test/fargate-cluster


    # Apply the Terraform destroy execution plan
    - name: Terraform Destroy
      run: terraform apply -destroy -auto-approve -var-file=../test.tfvars
      working-directory: ./environments/test/fargate-cluster

  task-definitions:
    name: 'task-definitions'
    runs-on: ubuntu-latest
    environment: test
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/test/task-definitions

    # Generates an execution plan for Terraform
    - name: Terraform Destroy Plan
      run: terraform plan -destroy -var-file=../test.tfvars
      working-directory: ./environments/test/task-definitions

    # Apply the Terraform destroy execution plan
    - name: Terraform Destroy
      run: terraform apply -destroy -auto-approve -var-file=../test.tfvars
      working-directory: ./environments/test/task-definitions

  bastion:
    name: 'bastion'
    runs-on: ubuntu-latest
    environment: test
    env:
      # Account and Environment
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/test/bastion

    # Generates an execution plan for Terraform
    - name: Terraform Destroy Plan
      run: terraform plan -destroy -var-file=../test.tfvars
      working-directory: ./environments/test/bastion

    # Apply the Terraform destroy execution plan
    - name: Terraform Destroy
      run: terraform apply -destroy -auto-approve -var-file=../test.tfvars
      working-directory: ./environments/test/bastion